# docker-compose
version: "3.5"

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/chmassa/data/mariadb'
  website:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/chmassa/data/wordpress'

services:
  mariadb:
    build: requirements/mariadb/
    image: mariadb:V1
    container_name: mariadb_inception42
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
    env_file: .env

  nginx:
    build: requirements/nginx/
    image: nginx:V1
    container_name: nginx_inception42
    ports:
      - "443:443"
    volumes:
      - website:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    restart: on-failure
    env_file: .env

  wordpress:
    build: requirements/wordpress/
    image: wordpress:V1
    container_name: wordpress_inception42
    ports:
      - "9000:9000"
    volumes:
      - website:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    restart: on-failure
    env_file: .env
